/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.BazaDanych;
import backend.Notatka;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mszwa
 */
public class WyswietlFrame extends javax.swing.JFrame {

    /**
     * Creates new form WyswietlFrame
     */
    public WyswietlFrame() {
        initComponents();
        bd=new BazaDanych();
        notatka=bd.pobierzNotatke();
        this.wyswietlNotatke(0);
  
    }
        private void wyswietlNotatke(int idNotatki) {
        tfNumer.setText(""+notatka.get(idNotatki).getNumer());
        tfNazwa.setText(""+notatka.get(idNotatki).getNazwa());
        tfPodanadata.setText(""+notatka.get(idNotatki).getPodanadata());
        tfOpis.setText(""+notatka.get(idNotatki).getOpis());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfOpis = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfNazwa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPodanadata = new javax.swing.JTextField();
        bWstecz = new javax.swing.JButton();
        bDalej = new javax.swing.JButton();
        tfNumer = new javax.swing.JTextField();

        tfOpis.setColumns(20);
        tfOpis.setRows(5);
        jScrollPane1.setViewportView(tfOpis);

        jLabel1.setText("Nazwa");

        jLabel2.setText("Data");

        tfPodanadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPodanadataActionPerformed(evt);
            }
        });

        bWstecz.setText("<");
        bWstecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWsteczActionPerformed(evt);
            }
        });

        bDalej.setText(">");
        bDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDalejActionPerformed(evt);
            }
        });

        tfNumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNumer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfPodanadata)
                                .addComponent(tfNazwa, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bWstecz)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bDalej))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tfNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPodanadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bWstecz)
                    .addComponent(bDalej))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPodanadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPodanadataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPodanadataActionPerformed

    private void tfNumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerActionPerformed

    private void bWsteczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWsteczActionPerformed
        // TODO add your handling code here:
        if(this.idNotatki>0) {
           idNotatki--;
           this.wyswietlNotatke(idNotatki);
       }
       else{
           JOptionPane.showMessageDialog(null,"Jesteś na pierwszej notatce" );
       }
    }//GEN-LAST:event_bWsteczActionPerformed

    private void bDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDalejActionPerformed
        // TODO add your handling code here:
        if(this.idNotatki<notatka.size()-1) {
           idNotatki++;
           this.wyswietlNotatke(idNotatki);
       }
       else{
           JOptionPane.showMessageDialog(null,"Jesteś na ostatniej notatce" );
       }
    }//GEN-LAST:event_bDalejActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WyswietlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WyswietlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WyswietlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WyswietlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WyswietlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDalej;
    private javax.swing.JButton bWstecz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfNazwa;
    private javax.swing.JTextField tfNumer;
    private javax.swing.JTextArea tfOpis;
    private javax.swing.JTextField tfPodanadata;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Notatka> notatka;
    private int idNotatki;
    private BazaDanych bd;
}
